partice_system_desc = {
--	auto_delete = 5,
	{	-- group0
		type = "sprite_view_align_xy",
		texture = "pfx_expl_01.tga",
		tex_animation = { 8, 4, 32, },
		flags = { "use_colors", "tex_animation", },
		fixed_size = { 15, 15, 15, },
		blend_type = "add",
--		alpha_test_type = "greater",
--		alpha_test_ref = 0,
		color = { { "point", 1, 1, 1, }, 1, },
--		size = { "point", 5, 5, 5, },
		velocity = { "blob", 0, 0, 250, 10, },
--		starting_age = { 2, 2, },
		rotation = { 0, 2, },
		angulat_vel = { 0, 2, },
		colliding = 1,
		actions = {
			{ "source", 10, { "point", 0, 0, 100, }, },
			{ "gravity", 0, 0, -200, },
			{ "bounce2", 0.2, 0.5, },
--			{ "vortex", 0, 0, 0, 0, 0, 1, 500000, },
--			{ "orbit_line", 0, 0, 0, 0, 0, 1, 500000, },
			{ "kill_old", 4, },
			{ "move", },
		},
	},
	{	-- group1
		type = "sprite_view_align_xy",
		texture = "pfx_expl_01.tga",
		tex_animation = { 8, 4, 32, },
		flags = { "use_colors", "tex_animation", },
		fixed_size = { 3, 3, 3, },
		blend_type = "add",
--		alpha_test_type = "greater",
--		alpha_test_ref = 0,
		color = { { "point", 1, 1, 1, }, 1, },
--		size = { "point", 5, 5, 5, },
		velocity = { "blob", 0, 0, 0, 5, },
--		starting_age = { 2, 2, },
		actions = {
			{ "source_from_group", 0, 100, },
--			{ "gravity", 0, 0, -200, },
			{ "damping", -5.0, -5.0, -5.0, },
			{ "kill_old", 1, },
			{ "move", },
		},
	},
}